debug: false
# ???? ?????? ?? ? ??? ???.
management.endpoints.web.exposure.include: "*"
# ?????? ????? ? ????? ???? ?? ??????. ?? ???? ???? ??? ?? ? ? ?? ??.

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    # ?? ???? ?? ???? request, response ??? ???? ???? ??.
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # jpa? ??? ? ?? ??? ??? ??? ??? ? ??. ? ? ??? ????? ???..?? ??? ? ?? ??.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: fastcampus
    password: thisIsTestPw^^
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
#    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true # ???? ??? ??? ??? ??? ?? ???.
        default_batch_fetch_size: 100 # bulk select ???? ?. ?? ?? ??? ?? 10 ?? ??? ?????? ?? ? ?? select ??? ???. ?? 100? ??? ??.
    open-in-view: false
  #  h2.console.enabled: true
  sql.init.mode: always # data.sql ??? ?????.
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true


---

# test db? ??....? ??? ???? ?? ?? document? ?? ? ??. spring?? ???? profile? ?? ????.
#spring:
#  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none;

---
spring:
  config:
    activate:
      on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa.hibernate.ddl-auto: create
  sql.init.mode: always
---